name: CI

on: [push, pull_request]

jobs:
  tests:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: NPM install and lint
        run: |
          npm ci
          npm run lint
